// Primeloop — shared Supabase client
// Public client key only. Database access is protected by Supabase RLS.
const SUPABASE_URL = "https://kzdcugbrgkkkqgsfkcje.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable__HGbH8s7sKZ83FTXHEvHJw_A76kzgPW";
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
function escapeHtml(str) { const div=document.createElement('div'); div.textContent=str||''; return div.innerHTML; }
function timeAgoOrDate(iso) { const d=new Date(iso); return d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}); }
const LOCAL_COVER_IMAGES={
'open-source-vs-proprietary-ai-small-business':'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=88',
'ai-search-vs-google':'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=88',
'ai-note-taking-apps-compared':'https://images.unsplash.com/photo-1456324504439-1ead2a0b7b7c?auto=format&fit=crop&w=1200&q=88',
'best-ai-coding-assistants-compared':'https://images.unsplash.com/photo-1461749280684-dccba630e2f?auto=format&fit=crop&w=1200&q=88',
'ai-agents-explained-2026':'https://images.unsplash.com/photo-1484417894907-623942c8ee29?auto=format&fit=crop&w=1200&q=88',
'ai-image-generators-compared':'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=1200&q=88',
'when-ai-tools-make-you-slower':'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=88',
'one-person-ai-ops-stack':'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=88'};
const EDITORIAL_POSTS=[
{slug:'ai-browser-agents-2026',title:'AI Browser Agents in 2026: What They Can Do, Where They Fail, and How to Use Them Safely',category:'AI Tools',excerpt:'AI browser agents can navigate websites, research information and complete multi-step tasks. Learn their capabilities, limits, risks and best practices.',read_time:'8 min',published_at:'2026-09-06T08:00:00Z',static_url:'/posts/ai-browser-agents-2026.html',cover_gradient:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=88'},
{slug:'mcp-2026-explained',title:'MCP in 2026 Explained: What Model Context Protocol Actually Does for AI Agents',category:'AI Tools',excerpt:'A practical developer-friendly guide to Model Context Protocol, MCP servers, tools, security and agent workflows.',read_time:'9 min',published_at:'2026-09-06T07:00:00Z',static_url:'/posts/mcp-2026-explained.html',cover_gradient:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-video-generators-2026',title:'AI Video Generators in 2026: Best Use Cases, Workflow Tips and What Actually Works',category:'AI Tools',excerpt:'AI video generators are moving into real production workflows. Learn where they save time and what still needs a human editor.',read_time:'8 min',published_at:'2026-09-06T06:00:00Z',static_url:'/posts/ai-video-generators-2026.html',cover_gradient:'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-voice-agents-2026',title:'AI Voice Agents in 2026: How Businesses Are Automating Calls Without Losing the Human Touch',category:'AI Tools',excerpt:'Where AI voice agents help businesses, where humans are still essential, and how to build a safer voice workflow.',read_time:'8 min',published_at:'2026-09-06T05:00:00Z',static_url:'/posts/ai-voice-agents-2026.html',cover_gradient:'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-agent-security-2026',title:'AI Agent Security in 2026: 9 Risks to Check Before Giving Agents Real Access',category:'AI Tools',excerpt:'A practical security checklist for teams deploying AI agents with tools, browser access and business permissions.',read_time:'9 min',published_at:'2026-09-06T04:00:00Z',static_url:'/posts/ai-agent-security-2026.html',cover_gradient:'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-meeting-assistants-2026',title:'AI Meeting Assistants in 2026: Best Workflows for Notes, Summaries and Follow-Ups',category:'Productivity',excerpt:'How to use AI meeting assistants for notes, decisions and follow-ups without creating more work.',read_time:'7 min',published_at:'2026-09-05T09:00:00Z',static_url:'/posts/ai-meeting-assistants-2026.html',cover_gradient:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-native-software-2026',title:'AI-Native Software in 2026: What Changes When AI Becomes Part of the Product',category:'AI Tools',excerpt:'How AI-native products differ from traditional SaaS and where the biggest opportunities are for builders.',read_time:'8 min',published_at:'2026-09-05T08:00:00Z',static_url:'/posts/ai-native-software-2026.html',cover_gradient:'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-coding-agents-2026',title:'AI Coding Agents in 2026: What Developers Need to Know',category:'AI Tools',excerpt:'AI coding agents are moving from autocomplete to autonomous software work. Learn what changed, where agents help, the risks, and how developers should adapt.',read_time:'9 min',published_at:'2026-09-05T08:00:00Z',static_url:'/posts/ai-coding-agents-2026.html',cover_gradient:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-search-seo-2026',title:'AI Search SEO in 2026: How to Get Found in AI Overviews and AI Mode',category:'Guide',excerpt:'What actually matters for SEO as Google Search adds more generative AI experiences, from useful content and internal links to images and structured data.',read_time:'8 min',published_at:'2026-09-05T07:00:00Z',static_url:'/posts/ai-search-seo-2026.html',cover_gradient:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-agents-small-business-2026',title:'AI Agents for Small Business in 2026: 7 Practical Use Cases',category:'AI Tools',excerpt:'Where AI agents can actually save time for small teams—and where human review still matters.',read_time:'8 min',published_at:'2026-09-05T06:00:00Z',static_url:'/posts/ai-agents-small-business-2026.html',cover_gradient:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=88'},
{slug:'local-ai-privacy-2026',title:'Local AI in 2026: Privacy, Performance and What Actually Runs on Your PC',category:'AI Tools',excerpt:'A practical guide to local AI, on-device models, privacy, hardware and the limits of running models locally.',read_time:'8 min',published_at:'2026-09-05T05:00:00Z',static_url:'/posts/local-ai-privacy-2026.html',cover_gradient:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=88'},
{slug:'ai-productivity-stack-2026',title:'How to Build an AI Productivity Stack in 2026 Without Tool Overload',category:'Productivity',excerpt:'Build a practical AI productivity stack with fewer tools. Learn how to choose AI apps for research, writing, meetings and automation.',read_time:'7 min',published_at:'2026-09-05T04:00:00Z',static_url:'/posts/ai-productivity-stack-2026.html',cover_gradient:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=88'}];
function getCoverUrl(post){const local=post&&post.slug?LOCAL_COVER_IMAGES[post.slug]:'';if(local)return local;const dbUrl=post&&post.cover_gradient;if(dbUrl&&/^https?:\/\//i.test(dbUrl))return dbUrl;return '';}
function postLink(post){return post&&post.static_url?post.static_url:'/post-template.html?slug='+encodeURIComponent(post.slug);}
function coverHtml(post,className='card-thumb'){const url=getCoverUrl(post);if(url)return `<div class="${className}" style="background-image:url('${escapeHtml(url)}');background-size:cover;background-position:center;"></div>`;return `<div class="${className}"><span class="glyph">${escapeHtml(post&&post.category?post.category[0]:'S')}</span></div>`;}
function postCardHtml(post){return `<article class="card"><a href="${postLink(post)}" style="display:contents;">${coverHtml(post)}<div class="card-body"><div class="card-meta"><span class="tag">${escapeHtml(post.category)}</span><span>·</span><span>${escapeHtml(post.read_time||'')}</span></div><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.excerpt||'')}</p></div></a></article>`;}
async function loadFeaturedPost(containerId){const el=document.getElementById(containerId);if(!el)return;const {data,error}=await sb.from('posts').select('*').eq('published',true).order('published_at',{ascending:false}).limit(1).single();if(error||!data){el.style.display='none';return;}el.innerHTML=`${coverHtml(data)}<div><div class="card-meta"><span>${escapeHtml((data.category||'').toUpperCase())}</span><span>·</span><span>${escapeHtml(data.read_time||'')} READ</span></div><h3><a href="${postLink(data)}">${escapeHtml(data.title)}</a></h3><p style="color:var(--paper-dim);margin:14px 0 20px;">${escapeHtml(data.excerpt||'')}</p><a href="${postLink(data)}" class="btn btn-ghost">Read full review →</a></div>`;}
async function loadLatestPosts(containerId,limit=6,category=null){const el=document.getElementById(containerId);if(!el)return;let query=sb.from('posts').select('*').eq('published',true).order('published_at',{ascending:false}).limit(Math.max(limit,100));if(category)query=query.eq('category',category);const {data,error}=await query;if(error){console.error('Latest posts load failed:',error);el.innerHTML='<p style="color:var(--paper-dim);">Could not load posts right now.</p>';return;}const dbPosts=data||[];const merged=[...dbPosts,...EDITORIAL_POSTS.filter(p=>!dbPosts.some(d=>d.slug===p.slug))].filter(p=>!category||p.category===category).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,limit);el.innerHTML=merged.length?merged.map(postCardHtml).join(''):'<p style="color:var(--paper-dim);">No posts yet — check back soon.</p>';}
